const ERROR_CODES = {
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_VERIFICATION_EXPIRED: 'EMAIL_VERIFICATION_EXPIRED',
  EXERCISE_NOT_FOUND: 'EXERCISE_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_EMAIL_VERIFICATION_TOKEN: 'INVALID_EMAIL_VERIFICATION_TOKEN',
  INVALID_PASSWORD_RESET_TOKEN: 'INVALID_PASSWORD_RESET_TOKEN',
  INVALID_REFRESH: 'INVALID_REFRESH',
  NOT_FOUND: 'NOT_FOUND',
  PASSWORD_RESET_EXPIRED: 'PASSWORD_RESET_EXPIRED',
  REFRESH_EXPIRED: 'REFRESH_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND'
};

module.exports = ERROR_CODES;
